dist:
  trusty
sudo:
  false

language:
  cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

env:
  - Coverage=ON BuildType=Release Implementation=Compact
  - Coverage=ON BuildType=Release Implementation=Optimised
  - Coverage=ON BuildType=Release Implementation=SIMD

before_script:
  - mkdir build && cd build
  - cmake
    -DCMAKE_BUILD_TYPE=$BuildType
    -DIMPLEMENTATION=$Implementation
    -DENABLE_COVERAGE=$Coverage
    -DCMAKE_VERBOSE_MAKEFILE=ON
    -DCMAKE_RULE_MESSAGES=OFF
    ..

script:
  - cmake --build . --parallel
  - ctest .

after_success:
  - bash <(curl -s https://codecov.io/bash)
