dist:
  trusty
sudo:
  false

language:
  cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang

env:
  - Implementation=Universal
  - Implementation=SSE2

before_script:
  - mkdir build && cd build
  - cmake
    -DCMAKE_BUILD_TYPE=$Release
    -DIMPLEMENTATION=$Implementation
    ..

script:
  - cmake --build .
  - ctest .
